# Generated by Django 5.0.1 on 2024-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='is_professional',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authors',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
