# Generated by Django 5.0.1 on 2024-01-18 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_models_delete_noticias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='receps',
        ),
    ]
