# Generated by Django 5.0.1 on 2024-01-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_rename_models_receps'),
    ]

    operations = [
        migrations.AddField(
            model_name='receps',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
