# Generated by Django 5.0.1 on 2024-01-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_receps_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receps',
            name='time',
            field=models.CharField(max_length=192),
        ),
    ]
