# Generated by Django 5.0.1 on 2024-01-22 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=38, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='cargo',
        ),
        migrations.CreateModel(
            name='Receps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=92)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('portions', models.IntegerField()),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=192)),
                ('slug', models.SlugField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='receps.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cargos',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
