# Generated by Django 5.0.1 on 2024-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receps', '0002_categories_remove_users_cargo_receps_delete_cargos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-utensils', max_length=100, null=True),
        ),
    ]
