# Generated by Django 4.2.5 on 2024-02-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receps', '0004_recipes_delete_receps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cover',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
