# Generated by Django 5.0.1 on 2024-01-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_users_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='senha',
        ),
        migrations.DeleteModel(
            name='Cargos',
        ),
    ]
