# Generated by Django 5.0.1 on 2024-01-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_remove_users_cargo_remove_users_senha_delete_cargos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
