from .middleware import *
from .installed_apps import *
from .database import *
from .validator import *
from .secret_key import SECRET_KEY
from .static import *
from .templates import *
from .i18n import *
from .django import *
